.changeset/long-maps-smash.md
src/internal/cause.ts
src/internal/fiberRuntime.ts
test/Effect/caching.ts
test/Effect/collecting.ts
test/Effect/destructors.ts
test/Effect/error-handling.ts
test/Effect/repeating.ts

Fix Cause and add more effect tests

---

.changeset/gentle-shirts-sin.md
src/Effect.ts
src/internal/effect.ts
src/internal/fiberRuntime.ts
test/Effect/destructors.ts
test/Effect/error-handling.ts
test/Effect/filtering.ts
test/Effect/forking.ts
test/Effect/sequencing.ts
test/Effect/traversing.ts
test/Schedule.ts

IN PROGRESS DO NOT MERGE :)
--
lol :)

Add additional Effect tests

---

.changeset/honest-bugs-hug.md
.vscode/debug.cjs
docs/modules/Debug.ts.md
examples/bench.ts
src/Debug.ts
src/internal/core.ts
src/internal/effect.ts
src/internal/fiberRuntime.ts

This PR is only a minimal step and adds just 1 `debugAs` for the purpose of developing the debugger extension, if the extension goes well we can propagate

Support execution debugger

---

.changeset/pink-spies-return.md
src/Config.ts
src/Config/Error.ts
src/Config/Provider.ts
src/internal/config.ts
src/internal/configError.ts
src/internal/configProvider.ts
test/Config.ts
test/ConfigProvider.ts

Enhancements to `Config` and `ConfigProvider`

---

.changeset/blue-rings-sit.md
.changeset/little-planets-smoke.md
src/Pool.ts
src/internal_effect_untraced/core.ts
src/internal_effect_untraced/pool.ts
test/Pool.ts

https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZPool.scala

Implement `Pool`

---

.changeset/early-hats-do.md
package.json
pnpm-lock.yaml
src/internal_effect_untraced/config.ts
src/internal_effect_untraced/configProvider.ts
src/internal_effect_untraced/defaultServices.ts
src/internal_effect_untraced/effect.ts
src/internal_effect_untraced/fiberRefs.ts
src/internal_effect_untraced/fiberRuntime.ts
src/internal_effect_untraced/layer.ts
src/internal_effect_untraced/metric.ts
src/internal_effect_untraced/metric/hook.ts
src/internal_effect_untraced/metric/key.ts
src/internal_effect_untraced/metric/registry.ts
src/internal_effect_untraced/schedule.ts
src/internal_effect_untraced/scopedRef.ts
src/internal_effect_untraced/testing/testServices.ts
test/Effect/environment.ts
test/Layer.ts

Upgrades `io` to include the latest `@fp-ts/data`, which fully supports dual function signatures.

Upgrade dependencies

---

.changeset/odd-foxes-explain.md
src/KeyedPool.ts
src/Pool.ts
src/internal_effect_untraced/keyedPool.ts
src/internal_effect_untraced/pool.ts
test/KeyedPool.ts

I'm open to suggestions on the naming of the constructors if we want to change them.

Add `KeyedPool`

---

docs/modules/Effect.ts.md
src/Effect.ts
test/Effect/validation.ts

@IMax153 @mikearnaldi this is the first `@example` of the package, I don't know whether the style is acceptable, let me know if you want me to change (or remove) it

validateFirst: clarify what happens if input is empty

---

.changeset/strange-kangaroos-clap.md
src/Effect.ts

Found a cool little typo I think

Fix Effect#gen adapter parameter type

---

README.md
docs/index.md

add link to new effect website <https://www.effect.website>. this should help newcomer to start from scratch

docs: add link to new effect website

---

.changeset/popular-roses-wave.md
src/internal_effect_untraced/metric/hook.ts

- ensure values are filled with 0's by using typed array
- mapWithIndex argument order
- while -> for loop in histogram

fix histogram Metric hook

---

.changeset/short-poets-itch.md
src/internal_effect_untraced/runtime.ts

Fixed typo in async fiber error message.

fix:  async fiber exception message typo

---

.changeset/smooth-kiwis-count.md
docs/modules/Request.ts.md
src/Request.ts

Allow `Request.makeCache` to accept `DurationInput` for `timeToLive`

---

.changeset/wicked-colts-itch.md
src/Effect.ts
src/internal/fiberRuntime.ts

- remove dual from all implementation
- simplify Effect.all types

all cleanup

---

.changeset/brave-monkeys-smell.md
src/internal/runtime.ts

Improve AsyncFiberException error message

---

.changeset/four-fireants-agree.md
docs/modules/Effect.ts.md
src/Effect.ts
src/internal/fiberRuntime.ts
test/utils/cache/ObservableResource.ts

We should double check for similar cases

Revert acquireRelease to have a variant for interruptible behaviour

---

.changeset/long-dancers-confess.md
src/internal/random.ts
test/Effect/memoization.ts
test/KeyedPool.ts

change Random.nextIntBetween upper bound to be exclusive

---

.changeset/thin-flowers-hang.md
src/Config/Error.ts
src/internal/configError.ts

Make the path delimiter used in ConfigError configurable

---

.changeset/empty-countries-complain.md
dtslint/Effect.ts
src/Effect.ts
src/internal/effect.ts

Fixes catchTag, catchTags, tapErrorTag type signatures. Closes #594

fix: fixed tagged error fn types

---

.changeset/nine-ligers-argue.md
docs/modules/Effect.ts.md
src/Effect.ts
src/internal/effect.ts

expose value in Effect.filterOrDie fallback function

---

.changeset/cuddly-brooms-invite.md
docs/modules/Effect.ts.md
src/Effect.ts
src/internal/fiberRuntime.ts

add concurrency and batching to replicateEffect

---

.changeset/fifty-mails-repair.md
.changeset/gorgeous-spoons-accept.md
.changeset/hungry-dryers-heal.md
.changeset/lucky-pumas-sin.md
.changeset/quick-rice-warn.md
.changeset/tricky-berries-yawn.md
docs/modules/Cause.ts.md
docs/modules/Effect.ts.md
docs/modules/Exit.ts.md
docs/modules/FiberId.ts.md
docs/modules/Runtime.ts.md
package.json
pnpm-lock.yaml
src/Cause.ts
src/Effect.ts
src/Exit.ts
src/FiberId.ts
src/Runtime.ts
src/internal/cause.ts
src/internal/core.ts
src/internal/fiberId.ts
src/internal/runtime.ts
test/Cause.ts
test/Effect/concurrency.ts
test/Effect/toString.ts
test/Exit.ts

Related: https://github.com/Effect-TS/data/issues/492
- make Cause Inspectable
- make Exit Inspectable
- make Effect Inspectable
- make FiberId inspectable
- make FiberFailure Inspectable

refactor toJSON / toString
