.changeset/bright-flowers-study.md
src/internal/cause.ts

```bash
gitpod /workspace/io (main) $ pnpm run example examples/defects.ts 
> @effect/io@0.0.5 example /workspace/io
> ts-node --project tsconfig.examples.json "examples/defects.ts"
╥
║
╠══╦══╗
║  ║  ║
║  ║  ╠─A checked error was not handled.
║  ║  ║ 
║  ║  ║ 0
║  ║  ║ 
║  ║  ║ Stack:
║  ║  ║ 
║  ║  ║ /workspace/io/examples/defects.ts:8:5
║  ║  ║ /workspace/io/examples/defects.ts:9:5
║  ║  ║ 
║  ║  ║ Execution:
║  ║  ║ 
║  ║  ║ /workspace/io/examples/defects.ts:8:16
║  ║  ║ /workspace/io/examples/defects.ts:8:5
║  ║  ║ /workspace/io/examples/defects.ts:12:17
║  ║  ║ 
║  ║  ▼
▼
```

fix cause rendering parallel segment

---

.changeset/rude-sheep-roll.md
docs/modules/Fiber/Runtime/Flags.ts.md
src/Fiber/Runtime/Flags.ts
src/internal/fiber.ts
src/internal/fiberRuntime.ts
src/internal/fiberScope.ts
src/internal/layer/circular.ts
src/internal/runtime.ts
src/internal/runtimeFlags.ts
test/RuntimeFlags.ts

Tracking facilities are implemented in ZIO in a way that it is easy for jvm debuggers to get information, namely modules are required. In JS debuggers can't really load modules reliably to inspect properties so roots should be tracked in a shared global object.

make trackig fibers global

---

.changeset/wicked-lemons-decide.md
src/Cause.ts
src/internal/cause.ts

We missed this method when porting `Cause`.

Add `Cause.flipCauseOption`

---

test/Effect/error-handling.ts

This PR makes sure to `await` `fc.asyncProperty` in tests that make use of it.

Fix tests using `fc.asyncProperty`

---

.changeset/cool-cycles-cheer.md
src/internal/logSpan.ts
src/internal/logger.ts
test/Logger.ts

I found a better heuristic here https://github.com/csquared/node-logfmt/blob/master/lib/stringify.js
but newlines also need escaping according to https://github.com/csquared/node-logfmt/issues/39
Instead I found that using `JSON.stringify` on the strings, seems to provide exactly what we need.
- addresses problems with space, double quote and equals inside key names; they aren't allowed.
- addresses problems with various escaping that has to occur within values, beyond just double quoting when spaces found.
we may now add double quotes when we don't need it, but at least we never not apply them when we do need them..

Improve stringlogger logfmt compatibility

---

.changeset/real-items-help.md
src/Effect.ts
src/internal_effect_untraced/effect.ts
test/Effect/error-handling.ts

ZIO has refineToOrDie to narrow the failure's channel type.
Since Effect has catchTag to perform narrowing on catch semantics, it only seems fitting to have a refineTagOrDie that performs similar narrowing logic automatically for refining semantics.
⚠️ first contribution, **review with extra attention** because I may have done stupid things! Most of the implementation is cargo-culted from catchTag and refineOrDie (especially trace / resolve stuff which I have no idea how it works).

feat(effect): add refineTagOrDie* operators

---

.changeset/metal-mirrors-change.md
src/Effect.ts
src/internal_effect_untraced/effect.ts
test/Effect/error-handling.ts

While the original implementation in bb7c80d is not incorrect, the callback's argument type was left unnecessarily wide making user DX not optimal.

refineTagOrDieWith: narrow callback argument type

---

.changeset/short-pots-sip.md
src/internal_effect_untraced/cause.ts
src/internal_effect_untraced/core.ts
src/internal_effect_untraced/runtime.ts

Changed behaviour of:
1) orElse variants to elect failures to defects in case a defect is present instead of silently losing the failure
2) catchAll variants to elect failures to defects in case a defect is present instead of silently losing the defect
We still recover with both 1 & 2 in case of multiple failures present, which seems to be an expected and wanted property given a test fails if I switch to elect failures to defects in case of multiple

Improve error semantics

---

.changeset/clean-candles-know.md
.gitignore
src/Effect.ts
src/internal_effect_untraced/effect.ts
test/Effect/error-handling.ts

It works like [`RTE.chainEitherKW`](https://gcanti.github.io/fp-ts/modules/ReaderTaskEither.ts.html#chaineitherkw) from fp-ts.
It's combinator for `pipe(Z.map(fn), Z.absolve)` -> `Z.absolveWith(fn)`

Add absolveWith function

---

.changeset/wild-donkeys-heal.md
docs/modules/Runtime.ts.md
src/Runtime.ts
src/internal_effect_untraced/runtime.ts
tsconfig.build.json

aligns with: `new Error("imm a message").stack`:
```
'Error: imm a message\n' +
'    at REPL19:1:11\n' +
'    at Script.runInThisContext (node:vm:129:12)\n' +
'    at REPLServer.defaultEval (node:repl:572:29)\n' +
'    at bound (node:domain:433:15)\n' +
'    at REPLServer.runBound [as eval] (node:domain:444:12)\n' +
'    at REPLServer.onLine (node:repl:902:10)\n' +
'    at REPLServer.emit (node:events:525:35)\n' +
'    at REPLServer.emit (node:domain:489:12)\n' +
'    at [_onLine] [as _onLine] (node:internal/readline/interface:422:12)\n' +
'    at [_line] [as _line] (node:internal/readline/interface:893:18)'
```

align FiberFailure stack with new Error().stack format.

---

.changeset/sharp-bats-whisper.md
docs/modules/Scheduler.ts.md
src/Scheduler.ts
src/internal_effect_untraced/clock.ts
src/internal_effect_untraced/effect.ts

Forbidding async for all the fiber tree is too unintuitive when running in sync

Remove tracking of execution mode

---

.changeset/flat-lions-accept.md
docs/modules/Effect.ts.md
docs/modules/Runtime.ts.md
docs/modules/Scheduler.ts.md
src/Effect.ts
src/Runtime.ts
src/Scheduler.ts
src/internal_effect_untraced/runtime.ts

While `orFiber` variants have use cases such use cases are so low level that most likely one would benefit from using runFork instead. While it is possible to maintain those variants it may be counter intuitive to get the fiber for `Exit<never, Exit<E, A>>` instead given the escape for logging that is now default in runX methods

Avoid logging final errors when using runPromise/runSync/runCallback, remove conditional orFiber

---

.changeset/quiet-bugs-tease.md
src/internal_effect_untraced/testing/testConfig.ts
src/internal_effect_untraced/testing/testServices.ts

While I was attempting to update /test https://github.com/Effect-TS/test/pull/6, I noticed that TestConfig's Tag is exported as TestClock, I updated the name to TestConfig

refactor: rename TestConfig Tag to TestConfig

---

.changeset/shiny-donkeys-hear.md
docs/modules/Cache.ts.md
docs/modules/ScopedCache.ts.md
src/Cache.ts
src/ScopedCache.ts
src/internal_effect_untraced/cache.ts
src/internal_effect_untraced/scopedCache.ts
test/ScopedCache.ts

feat: getOptionComplete for Cache and ScopedCache

---

.changeset/red-deers-raise.md
src/Metric.ts
src/Metric/Key.ts
src/internal_effect_untraced/metric.ts
src/internal_effect_untraced/metric/key.ts
test/Metric.ts

See [here](https://github.com/zio/zio/pull/8159) for motivation.

Support a `description` field in `MetricKey`

---

.changeset/grumpy-wombats-peel.md
.vscode/snippets.code-snippets
src/internal_effect_untraced/configProvider.ts
test/ConfigProvider.ts

This PR fixes `ConfigProvider.orElse` which currently doesn't work with combination of nesting and indexed data.

Fix nesting for `ConfigProvider.orElse`

---

.changeset/silver-ties-wave.md
.changeset/strong-taxis-thank.md
.changeset/unlucky-dryers-compete.md
docs/modules/Effect.ts.md
examples/order.ts
package.json
pnpm-lock.yaml
src/Effect.ts
src/internal/core.ts
src/internal/dataSource.ts
src/internal/effect.ts
src/internal/fiberRuntime.ts
src/internal/hub.ts
src/internal/layer.ts
src/internal/pool.ts
src/internal/reloadable.ts
src/internal/resource.ts
src/internal/scopedCache.ts
src/internal/testing/testClock.ts
test/Effect/acquire-release.ts
test/Effect/async.ts
test/Effect/concurrency.ts
test/Effect/filtering.ts
test/Effect/finalization.ts
test/Effect/interruption.ts
test/Fiber.ts
test/Layer.ts
test/Pool.ts
test/utils/cache/ObservableResource.ts

Reverts the following back to positional arguments:
Fixes the spelling of `interruptable` -> `interruptible`.
Closes #498
Closes #499

Fix typing regressions with object args for certain combinators

---

.github/workflows/main.yml
.github/workflows/pr.yml
dtslint/Effect.ts
dtslint/index.d.ts
dtslint/tsconfig.json
package.json
pnpm-lock.yaml
src/Runtime.ts

(@tim-smart moved `interface FiberFailure` after `NodePrint` because of a compilation error with typescript v4.9 while running the type-level tests)

add dtslint tests

---

.changeset/yellow-carpets-end.md
docs/modules/Effect.ts.md
src/Effect.ts

as title mentions, the docs reference `tryCatchPromise` which has
merged with `tryPromise` and got removed

Change doc from referencing tryCatchPromise into tryPromise

---

.changeset/good-boxes-suffer.md
.changeset/large-planets-worry.md
.changeset/selfish-bikes-own.md
docs/modules/Effect.ts.md
src/Effect.ts
src/internal/clock.ts
src/internal/core.ts
src/internal/effect.ts
src/internal/effect/circular.ts
test/Effect/async.ts
test/Effect/interruption.ts

Effect.async and Effect.asyncInterrupt can be merged into 1 function.

align Interrupt apis and add optional interruption to async api

---

.changeset/tidy-carpets-act.md
dtslint/Effect.ts
src/Effect.ts
src/internal/effect.ts
test/Effect/tapping.ts

feat: added Effect.tapErrorTag

---

.changeset/angry-jars-begin.md
docs/modules/Config/Error.ts.md
docs/modules/Effect.ts.md
src/Effect.ts
src/internal/effect.ts

This is a recurring helper I keep writing to be able to zoom "in" on the optionality of some `Effect<R, E, Option<A>>` (usually more than one), usually with `Effect.flatten` resulting in `Effect<R, E | Cause.NoSuchElementException, A>`. This is really nice for working with optionality within an Effect-based workflow, but there is not built-in for the "reverse" operation. 
I'm 110% open to bikeshedding on a better name for this operator, but this seems like a gap in the interop with Option.

add optionFromOptional

---

examples/order.ts
src/internal/effect.ts
test/Effect/foreign.ts
test/ScopedCache.ts
test/utils/cache/WatchableLookup.ts

... just some house keeping.
This removes all the redundant pipe() calls.

remove double pipes

---

.changeset/metal-forks-nail.md
src/internal/effect.ts
test/Effect/cause-rendering.ts

Avoid losing annotations when catchTag / catchTags fail to recover

---

.changeset/mean-geckos-hunt.md
docs/modules/Exit.ts.md
src/Exit.ts
src/internal/core.ts

- Relaxed `match` `getOrElse` and `matchEffect` signatures
- Fixed small bug in internal module with signatures

Use less strict signatures in Exit module

---

.changeset/good-spiders-matter.md
src/Queue.ts
src/internal/queue.ts

The curried variant of `Queue.offerAll` is type incorrectly accepting 2 separate Enqueues. This just removes the second to fix the signature.

fix: Queue.offerAll curried signature

---

.changeset/curly-geese-brake.md
src/internal/timeout.ts

fix regression introduced by bun timeout hotfix
